name: doc-emb
channels:
  - pytorch
dependencies:
  - pytorch=1.8.1
  - torchvision
  - sentence_transformers
  - laserembeddings
  - mcerp
  - torchaudio
  - python=3.8
  - pip
  - tqdm
  - numpy
  - matplotlib==3.3.3
